/// Flutter icons PetCodeIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PetCodeIcons
///      fonts:
///       - asset: fonts/PetCodeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PetCodeIcons {
  PetCodeIcons._();

  static const _kFontFam = 'PetCodeIcons';
  static const String _kFontPkg = null;

  static const IconData treat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_vaccination = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addphoto = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calenderage = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cat_1 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData color = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comb = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog_walk = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email_1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paw = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData petinfo = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pill = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_plain = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poop = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_owner = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData safety = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scanlocations = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData service = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stats = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData syringe_plus = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_168 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poster = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medicalicon = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
